services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
#      DATABASE_URL: postgres://user:password@postgres:5432/server-db
      DATABASE_URL: "postgresql://user:password@postgres:5432/server-db?schema=public"
    depends_on:
      - postgres

volumes:
  postgres:





#services:
#  server:
#    build:
#      context: ./server
#    volumes:
#      - ./server:/app
#    ports:
#      - "3000:3000"
#    environment:
#      DATABASE_URL: postgres://user:password@postgres:5432/server-db
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres:13.5
#    restart: always
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#
#volumes:
#  postgres:












#services:
#  server:
#    build:
#      context: ./server
#      dockerfile: ../Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - "3000:3000"
#    environment:
#      DATABASE_URL: postgres://user:password@postgres:5432/server-db
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres:13.5
#    restart: always
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#
#volumes:
#  postgres:
#




#version: '3.8'
#services:
#  postgres:
#    image: postgres:13.5
#    restart: always
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#
#  server:
#    build: ..
#    ports:
#      - '3000:3000'
#    environment:
#      DATABASE_URL: postgres://user:password@postgres:5432/server-db
#    depends_on:
#      - postgres
#
#volumes:
#  postgres:






#version: '3.8'
#services:
#  postgres:
#    image: postgres:13.5
#    restart: always
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=server-db
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#
#  server:
#    build: ./server
#    ports:
#      - '3000:3000'
#    environment:
#      - DATABASE_URL=postgresql://user:password@postgres:5432/server-db?schema=public
#    depends_on:
#      - postgres
#
#volumes:
#  postgres:




#version: '3.8'
#services:
#
#  postgres:
#    image: postgres:13.5
#    restart: always
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#
#volumes:
#  postgres:
